### ISSUE TITLE
Instability issues

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#30]
Being honest with you this mod pack needs an update just to fix the stability of it

two things that need to be done
A) NEI useage crashes
B) BCA GUI crashes 

Fix them please - making me not want to play this mod pack at all

**Comment by AlexTheGre4t** [comment]
There's a reason why i keep saying this is an alpha. Plus I've been extremely busy over the past few days and have had little to no time working on the pack.

**Comment by AEnterprise** [comment]
i don't know anything about BCA gui crashes, crashlogs please so i can get them fixed

also if you have BCA releated issue please ping me

**Comment by Xariyl** [comment]
I thought the BCA crash was fixed with the last update. Are you still having issues?

(Original issue opened here: 
https://github.com/AlexTheGre4t/MCTNG/issues/4 )

**Comment by ryuben** [comment]
I'm not picking at you Alex.

And yes x me and iixia, was bouncing off last night.

I will report that removing upgrades works well

i don't know anything about BCA gui crashes, crashlogs please so i can get
them fixed

also if you have BCA releated issue please ping me

**Comment by AEnterprise** [comment]
oh those crashes, those are not BCA but eureka, those won't be fixed yet in the update of the pack yet, i hope to get a new BCA out very soon

**Comment by ryuben** [comment]
Sounds good ae, sooner the better nothing like Russian roulette when
checking on a machine lol

**Comment by Xariyl** [comment]
Think of it as a mini-game!

**Comment by AlexTheGre4t** [comment]
An annoying one along with the NEI ones, i can definitely look at the NEI one tonight, but ive had a hard time isolating the problem.

**Comment by AlexTheGre4t** [comment]
Woo, i found the issue with NEI, it was some minetweaker file issue. Anyway, thats completely fixed. We'll just have to wait until BCA is updated to fix the GUI crashes as well

**Comment by Xariyl** [comment]
Cool. Something we can fix on the server now, or need to wait?

**Comment by AEnterprise** [comment]
BCA and eureka are comming real sone, it's as good as done, mainly needs testing now

**Comment by AlexTheGre4t** [comment]
You'll have to wait on that Xariyl, there's a lot of changes coming with it to make everything a little more stable :D

**Comment by AEnterprise** [comment]
yeah, eureka should make those crashes go away, but i need more tests to make absolutely sure i'm not creating any new crashes/issues

**Comment by ryuben** [comment]
yaaaay

**Comment by Xariyl** [comment]
I know you were wanting to wait on the update, but is there ANYTHING we can do about the NEI crashes now? It is maddening to get crashed to desktop every few minutes.

**Comment by ryuben** [comment]
And especially since it takes me a few mins to get back into game

**Comment by AEnterprise** [comment]
i have no idea where he is waiting for on for updating

**Comment by AlexTheGre4t** [comment]
Remove any AE2 inscriber code in the AE2.zs file. They're all in the same place so it's easy to find. Updating NEI also fixes another crash issue but that's quite minor and can wait. I do get back for tomorow night so I can get something out then.

**Comment by Xariyl** [comment]
NEI crashes when looking at pretty much any recipe, now. This particular one was when looking at the potential uses for the Iron Stick (from BCA). The Assembly Table saves the previous recipes and I couldn't click the creation-toggle off fast enough, and ended up with several that I don't need. So I was curious to see what else they could be used for. Mouse-over over stick, press "U", and crash to desktop.

using MCTNG v 3.0.0.3

```
[13:32:29] [Netty IO #11/ERROR]  [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.7.0_71]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.7.0_71]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.7.0_71]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.7.0_71]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.7.0_71]
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
[13:32:29] [Server thread/INFO]: Xariyl lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[13:32:29] [Server thread/INFO]: [OP] §rXariyl left the game
```

:cry:

**Comment by AEnterprise** [comment]
hmm, for the exesive sticks: i'll maybe bump up how much power you need to make them as a new way  of preventing to much overcrafting
